name: Sadew Mini Bot Run

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Start SADEW-MINI-MD
      env:
        G_TOKEN: ${{ secrets.G_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
        GITHUB_USERNAME: 'sadewrashmika13'  # 👈 උඹේ GitHub නම
        OWNER_NAME: 'sadewrashmika13'       # 👈 බොට් සොයන පොදු විචල්‍යයන්
        REPO_NAME: 'Sadew-mini'             # 👈 උඹේ රෙපෝ එකේ නම
      run: node index.js
